name: Java CI with Gradle

on:
  push:
    branches:
      - develop

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # (1) GitHub 저장소에서 코드를 체크아웃
      - name: checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      # (2) 서버에 SSH로 접속하여 코드 업데이트 및 배포
      - name: Deploy Images with Docker compose
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_SSH_HOST }}
          port: ${{ secrets.REMOTE_SSH_PORT }}
          username: ${{ secrets.REMOTE_SSH_ID }}
          password: ${{ secrets.REMOTE_SSH_PASSWD }}
          script_stop: true
          script: |
            set -e
            # (2-1) JDK 설치 확인 및 설치
            if ! java -version 2>&1 | grep -q "openjdk version \"17\""; then
                sudo apt update
                sudo apt install -y openjdk-17-jdk
            fi
            
            # (2-2) 프로젝트 디렉토리로 이동
            cd DocTech/DocTech-backend
            
            # (2-3) 최신 코드로 업데이트
            git pull origin dev
            git submodule update --init --recursive
            
            # (2-4) Gradle로 소스코드 빌드
            chmod +x ./gradlew
            ./gradlew clean build -x test
            
            # (2-5) Docker Compose로 기존 컨테이너 종료 및 재시작
            docker-compose -p doctech down
            docker-compose -p doctech up --build -d